name: Zip repo on push
on: [push]
jobs:
  Zip-Repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1
        with:
          args: rm -if about-magello.zip &&  zip -r about-magello.zip . -x "*.git*" -x "*.DS_Store"
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'about-magello.zip'
          message: 'Updated about-magello.zip'
          default_author: github_actor
